Repository EnterpriseDB/edb-ansible, pull requests merged in 2020-12, with the labels that each got.

#73 Rel cascaded replica
  roles/setup_efm/defaults/main.yml
  roles/setup_efm/tasks/efm_configure.yml
  roles/setup_replication/defaults/main.yml
  roles/setup_replication/tasks/main.yml
  roles/setup_replication/tasks/pg_basebackup.yml
  roles/setup_replication/tasks/setup_replication.yml
  roles/setup_replication/tasks/upstream_node.yml
  roles/setup_replication/tasks/upstream_node_slots.yml
Labels: REL_2_0_3

#76 Making setup_replication and setup_efm roles to use new format
  roles/init_dbserver/defaults/main.yml
  roles/init_dbserver/tasks/init_dbserver.yml
  roles/init_dbserver/tasks/main.yml
  roles/init_dbserver/tasks/pg_set_superuser_password.yml
  roles/init_dbserver/tasks/pg_ssl_check.yml
  roles/install_dbserver/tasks/install_dbserver.yml
  roles/install_dbserver/tasks/main.yml
  roles/manage_dbserver/defaults/main.yml
  roles/manage_dbserver/tasks/generate_password.yml
  roles/manage_dbserver/tasks/manage_db.yml
  roles/manage_dbserver/tasks/manage_extensions.yml
  roles/manage_dbserver/tasks/manage_hba_conf.yml
  roles/manage_dbserver/tasks/manage_pgpass.yml
  roles/manage_dbserver/tasks/manage_postgres_params.yml
  roles/manage_dbserver/tasks/manage_privileges.yml
  roles/manage_dbserver/tasks/manage_slots.yml
  roles/manage_dbserver/tasks/manage_users.yml
  roles/setup_efm/README.md
  roles/setup_efm/defaults/main.yml
  roles/setup_efm/tasks/create_efm_user.yml
  roles/setup_efm/tasks/efm_cluster_set_params.yml
  roles/setup_efm/tasks/efm_configure.yml
  roles/setup_efm/tasks/efm_set_params.yml
  roles/setup_efm/tasks/efm_start_service.yml
  roles/setup_efm/tasks/efm_stop_service.yml
  roles/setup_efm/tasks/main.yml
  roles/setup_efm/tasks/prepare_hba_value_list.yml
  roles/setup_efm/tasks/setup_efm.yml
  roles/setup_replication/README.md
  roles/setup_replication/defaults/main.yml
  roles/setup_replication/tasks/configure_node.yml
  roles/setup_replication/tasks/main.yml
  roles/setup_replication/tasks/pg_basebackup.yml
  roles/setup_replication/tasks/prepare_hba_value_list.yml
  roles/setup_replication/tasks/prepare_standby_slots_list.yml
  roles/setup_replication/tasks/primary_settings.yml
  roles/setup_replication/tasks/primary_synchronous_param.yml
  roles/setup_replication/tasks/setup_replication.yml
  roles/setup_replication/tasks/upstream_node.yml
  roles/setup_replication/tasks/upstream_node_slots.yml
  roles/setup_repo/tasks/main.yml
  roles/setup_repo/tasks/setup_repo.yml
Labels: REL-3_0_0

#80 Do not replace special chars in sync standby names
  roles/setup_replication/tasks/setup_replication.yml
Labels: REL-3_0_0

#77 Split setup_pem into setup_pemserver and setup_pemagent
  lookup_plugins/pem_agents.py
  lookup_plugins/pem_server.py
  lookup_plugins/pg_sr_cluster_nodes.py
  roles/init_dbserver/vars/EPAS.yml
  roles/init_dbserver/vars/PG.yml
  roles/setup_pem/.travis.yml
  roles/setup_pem/tasks/main.yml
  roles/setup_pem/tasks/setup_pemagent.yml
  roles/setup_pem/tests/inventory
  roles/setup_pem/tests/test.yml
  roles/setup_pemagent/README.md
  roles/setup_pemagent/defaults/main.yml
  roles/setup_pemagent/meta/main.yml
  roles/setup_pemagent/tasks/linux_update_etc_hosts.yml
  roles/setup_pemagent/tasks/main.yml
  roles/setup_pemagent/tasks/pem_agent_config.yml
  roles/setup_pemagent/tasks/pem_agent_fetch_adm_password.yml
  roles/setup_pemagent/tasks/pem_agent_hba.yml
  roles/setup_pemagent/tasks/pem_agent_install.yml
  roles/setup_pemagent/tasks/pem_agent_register_db.yml
  roles/setup_pemagent/tasks/pem_agent_user.yml
  roles/setup_pemagent/tasks/prepare_hba_value_list.yml
  roles/setup_pemagent/tasks/setup_pemagent.yml
  roles/setup_pemagent/vars/EPAS.yml
  roles/setup_pemagent/vars/PG.yml
  roles/setup_pemserver/README.md
  roles/setup_pemserver/defaults/main.yml
  roles/setup_pemserver/meta/main.yml
  roles/setup_pemserver/tasks/linux_update_etc_hosts.yml
  roles/setup_pemserver/tasks/main.yml
  roles/setup_pemserver/tasks/pem_server_config.yml
  roles/setup_pemserver/tasks/pem_server_hba.yml
  roles/setup_pemserver/tasks/pem_server_install.yml
  roles/setup_pemserver/tasks/pem_server_probe_alert.yml
  roles/setup_pemserver/tasks/pem_server_user.yml
  roles/setup_pemserver/tasks/prepare_hba_value_list.yml
  roles/setup_pemserver/tasks/rm_pem_server_install.yml
  roles/setup_pemserver/tasks/setup_pemserver.yml
  roles/setup_pemserver/vars/EPAS.yml
  roles/setup_pemserver/vars/PG.yml
Labels: REL-3_0_0

#82 Adapt PgpoolII roles for inventory file usage
  lookup_plugins/pg_sr_cluster_nodes.py
  roles/manage_pgpool2/README.md
  roles/manage_pgpool2/defaults/main.yml
  roles/manage_pgpool2/tasks/main.yml
  roles/manage_pgpool2/vars/EPAS.yml
  roles/manage_pgpool2/vars/PG.yml
  roles/setup_pgpool2/README.md
  roles/setup_pgpool2/defaults/main.yml
  roles/setup_pgpool2/tasks/main.yml
  roles/setup_pgpool2/tasks/pgpool2_configure_backend_pg_hba.yml
  roles/setup_pgpool2/tasks/pgpool2_configure_backends.yml
  roles/setup_pgpool2/tasks/pgpool2_configure_loadbalancing.yml
  roles/setup_pgpool2/tasks/pgpool2_restart_service.yml
  roles/setup_pgpool2/tasks/pgpool2_setup_sr_mode.yml
  roles/setup_pgpool2/tasks/pgpool2_setup_ssl.yml
  roles/setup_pgpool2/tasks/pgpool2_setup_watchdog.yml
  roles/setup_pgpool2/vars/EPAS.yml
  roles/setup_pgpool2/vars/PG.yml
Labels: REL-3_0_0

#98 Add Makefile for publishing in Galaxy
  Makefile
  galaxy.template.yml
Labels: REL-3_0_0

#99 Improve firewalld usage
  roles/init_dbserver/tasks/init_dbserver.yml
  roles/setup_efm/defaults/main.yml
  roles/setup_efm/tasks/efm_configure.yml
  roles/setup_efm/tasks/setup_efm.yml
  roles/setup_pemserver/tasks/setup_pemserver.yml
  roles/setup_pgbouncer/tasks/pgbouncer_setup.yml
  roles/setup_pgpool2/tasks/pgpool2_setup.yml
  roles/setup_replication/tasks/setup_replication.yml
Labels: REL-3_0_0

#100 Fixing the situation where firewalld is not installed on the system
  roles/init_dbserver/tasks/init_dbserver.yml
  roles/setup_efm/tasks/setup_efm.yml
  roles/setup_pemserver/tasks/setup_pemserver.yml
  roles/setup_pgbouncer/tasks/pgbouncer_setup.yml
  roles/setup_pgpool2/tasks/pgpool2_setup.yml
  roles/setup_replication/tasks/setup_replication.yml
Labels: REL-3_0_0

#101 Auto-tuning role
  README.md
  playbook.yml
  roles/autotuning/README.md
  roles/autotuning/defaults/main.yml
  roles/autotuning/meta/main.yml
  roles/autotuning/tasks/autotuning.yml
  roles/autotuning/tasks/install_tuned.yml
  roles/autotuning/tasks/main.yml
  roles/autotuning/tasks/setup_tuned.yml
  roles/autotuning/tasks/tune_postgres.yml
  roles/autotuning/templates/tuned.conf.template
  roles/autotuning/vars/EPAS.yml
  roles/autotuning/vars/PG.yml
  vars_plugins/host_supported_roles.py
Labels: enhancement
